name: deploy page

on:
  push:
    branches:
      - main
  watch:
    types: [started]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install
        run: npm i
      - name: build
        run: npm run build
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_HUB_TOKEN }}
          publish_dir: ./dist
